import Head from "next/head";
import Category from "../components/Header/Category";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import Products from "../components/Products/Products";

export default function Home({ products }) {
  return (
    <div className="text-gray-500 ">
      <Head>
        <title>Your favorite online store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" h-screen">
        <Hero />
      </main>

      <Category />
      <Products products={products} />
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch("https://fakestoreapi.com/products");
  const data = await response.json();

  return {
    props: {
      products: data,
    },
  };
}
