import Head from "next/head";
import Seller from "../components/Seller/Seller";
export default function Home({ products }) {
  return (
    <div className="text-gray-500 max-w-7xl mx-auto">
      <Head>
        <title>Your favorite online store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" ">
        <Seller />
      </main>
    </div>
  );
}
